INSERT INTO [dbo].[Student] ([Meno], [Priezvisko], [DatumNarodenia]) VALUES (N'Josef', N'Novák', N'1995-01-01')
INSERT INTO [dbo].[Student] ([Meno], [Priezvisko], [DatumNarodenia]) VALUES (N'Jan', N'Novotný', N'1996-02-25')
INSERT INTO [dbo].[Student] ([Meno], [Priezvisko], [DatumNarodenia]) VALUES (N'Albert', N'Einstein', N'1997-01-01')
INSERT INTO [dbo].[Student] ([Meno], [Priezvisko], [DatumNarodenia]) VALUES (N'Isaac', N'Newton', N'1993-01-04')
INSERT INTO [dbo].[Student] ([Meno], [Priezvisko], [DatumNarodenia]) VALUES (N'Pavla', N'Nová', N'1994-07-05')
INSERT INTO [dbo].[Student] ([Meno], [Priezvisko], [DatumNarodenia]) VALUES (N'Karel', N'Novák', N'1994-05-05')
INSERT INTO [dbo].[Student] ([Meno], [Priezvisko], [DatumNarodenia]) VALUES (N'Karel', N'Novotný', N'1994-05-06')
